units metal
atom_style atomic
boundary p p p

box tilt large
read_data alpha_quartz.data

pair_style vashishta
pair_coeff * * SiO.1997.vashishta O Si

mass  1 15.9994
mass  2 28.08

timestep 0.001

thermo 10
thermo_style custom step time temp pe etotal pxx pyy pzz pxy pxz pyz lx ly lz xy yz xz press vol spcpu cpuremain

dump 1 all custom 10000 trajectory.bin id type x y z

log log.lammps

velocity all create 298 64526 dist gaussian
fix npt all npt temp 298 298 1.0 x 1 1 1 y 1 1 1 z 1 1 1 tchain 10 pchain 10 nreset 1000

run 100000

unfix npt

fix npt all npt temp 298 298 1.0 x 1 200000 10 y 1 200000 10 z 1 200000 10 tchain 10 pchain 10 nreset 10000

run 10000000

write_data relaxed.data
